# Generated by Django 5.1.6 on 2025-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_signup_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.EmailField(default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
