# Generated by Django 5.1.6 on 2025-02-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_signup_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
